package com.juanite.model;

public enum Genres {
    NONE,CLASICA, BLUES, JAZZ, COUNTRY, SWING, ROCK, RB, FUNK,
    REGGAE, DISCO, METAL, PUNK_ROCK, HIP_HOP, NEW_WAVE,
    SYMTHPOP, EDM, HOUSE, TECHNO, GRUNGE, BRITPOP, TRANCE,
    INDIE_ROCK, POP_PUNK, EMO, POP_ROCK, K_POP, REGGAETON,
    DUBSTEP, BREAKBEAT, HARDCORE, TRAP, RAP;
}
